# Generated by Django 5.2.6 on 2026-07-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conceptocontable",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Concepto",
                "verbose_name_plural": "Conceptos",
            },
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="aplica_aniversario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="aplica_beneficencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="aplica_capitas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="aplica_otros",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="aplica_taller_bj",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="orden",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="requiere_hermano",
            field=models.BooleanField(default=True, verbose_name="Requiere hermano"),
        ),
        migrations.AddField(
            model_name="conceptocontable",
            name="tipo",
            field=models.CharField(
                choices=[("I", "Ingreso"), ("E", "Egreso")], default="I", max_length=1
            ),
        ),
    ]
