# Generated by Django 5.2.6 on 2026-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_conceptocontable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10)),
                ('orden', models.PositiveSmallIntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='conceptocontable',
            options={'ordering': ['nombre'], 'verbose_name': 'Concepto Contable', 'verbose_name_plural': 'Conceptos Contables'},
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='aplica_aniversario',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='aplica_beneficencia',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='aplica_capitas',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='aplica_otros',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='aplica_taller_bj',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='requiere_hermano',
        ),
        migrations.RemoveField(
            model_name='conceptocontable',
            name='tipo',
        ),
    ]
