# Generated by Django 5.2.6 on 2026-07-22 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_parametrosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionCapita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('concepto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino', to='catalogos.conceptocontable')),
                ('concepto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origen', to='catalogos.conceptocontable')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TarifaObligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligatoria', models.BooleanField(default=True)),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual'), ('EVENTUAL', 'Eventual')], default='MENSUAL', max_length=20)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.conceptocontable')),
            ],
            options={
                'ordering': ['concepto__nombre'],
            },
        ),
    ]
