# Generated by Django 5.2.6 on 2026-07-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_distribucioncapita_tarifaobligacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptocontable',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='conceptocontable',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
