# Generated by Django 5.2.6 on 2026-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_remove_conceptocontable_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucioncapita',
            name='grupo',
            field=models.CharField(default='LOCAL', max_length=20),
        ),
    ]
