# Generated by Django 5.2.6 on 2026-07-25 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("negocio", "0002_pago_aplicacionpago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="Folio"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("VIGENTE", "Vigente"), ("CANCELADO", "Cancelado")],
                        default="VIGENTE",
                        max_length=15,
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de cancelación"
                    ),
                ),
                (
                    "emitido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emitido por",
                    ),
                ),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibo",
                        to="negocio.pago",
                        verbose_name="Pago",
                    ),
                ),
            ],
            options={
                "ordering": ["-folio"],
            },
        ),
    ]
