# Generated by Django 5.2.6 on 2026-08-03 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('negocio', '0002_pago_aplicacionpago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['-folio'], 'verbose_name': 'Recibo', 'verbose_name_plural': 'Recibos'},
        ),
        migrations.CreateModel(
            name='ComprobanteTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comprobantes_transferencia/%Y/%m/', verbose_name='Comprobante bancario')),
                ('folio_bancario', models.CharField(max_length=100, unique=True, verbose_name='Folio o referencia bancaria')),
                ('emisor', models.CharField(max_length=150, verbose_name='Emisor según el comprobante')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto según el comprobante')),
                ('fecha_transferencia', models.DateField(blank=True, null=True, verbose_name='Fecha de la transferencia')),
                ('verificado_en', models.DateTimeField(auto_now_add=True, verbose_name='Verificado el')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_transferencia', to='negocio.pago', verbose_name='Pago')),
                ('verificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Comprobante de Transferencia',
                'verbose_name_plural': 'Comprobantes de Transferencia',
                'ordering': ['-verificado_en'],
            },
        ),
    ]
