# Generated by Django 5.2.6 on 2026-08-03 19:07

import django.core.validators
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_recibo_options_comprobantetransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantetransferencia',
            name='archivo',
            field=models.FileField(upload_to='comprobantes_transferencia/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), documentos.models.validar_tamano_comprobante], verbose_name='Comprobante bancario'),
        ),
    ]
