# Generated by Django 5.2.6 on 2026-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hermano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_control",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Control"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=100, verbose_name="Apellido Paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellido Materno"
                    ),
                ),
                (
                    "nombre_simbolico",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nombre Simbólico"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_alta",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de Alta"),
                ),
            ],
            options={
                "verbose_name": "Hermano",
                "verbose_name_plural": "Hermanos",
                "ordering": ["apellido_paterno", "apellido_materno", "nombre"],
            },
        ),
    ]
