# Generated by Django 5.2.6 on 2026-07-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermano',
            name='activo',
        ),
        migrations.AddField(
            model_name='hermano',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hermano',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hermano',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'Licencia'), ('SUSPENDIDO', 'Suspendido'), ('BAJA', 'Baja'), ('FALLECIDO', 'Fallecido')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_aumento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_exaltacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_iniciacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='hermanos/'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='grado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aprendiz'), (2, 'Compañero'), (3, 'Maestro')], default=1),
        ),
        migrations.AddField(
            model_name='hermano',
            name='logia_procedencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hermano',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hermano',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hermano',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hermano',
            name='profesion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hermano',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hermano',
            name='tipo_ingreso',
            field=models.CharField(choices=[('INICIACION', 'Iniciación'), ('AFILIACION', 'Afiliación'), ('REGULARIZACION', 'Regularización')], default='INICIACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='apellido_paterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='nombre_simbolico',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
