# Generated by Django 5.2.6 on 2026-07-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_grado_alter_conceptocontable_options_and_more'),
        ('miembros', '0002_remove_hermano_activo_hermano_celular_hermano_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.grado', verbose_name='Grado'),
        ),
    ]
