# Generated by Django 5.2.6 on 2026-08-03 19:07

import miembros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_alter_hermano_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='hermanos/', validators=[miembros.models.validar_tamano_fotografia]),
        ),
    ]
