# Generated by Django 4.2.11 on 2026-07-29 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0008_distribucioncapita_grupo'),
        ('miembros', '0003_alter_hermano_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('oriente', models.CharField(blank=True, max_length=150)),
                ('rito', models.CharField(blank=True, max_length=150)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logia',
                'verbose_name_plural': 'Logias',
                'ordering': ['nombre', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='hermano',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hermanos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hermano',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hermanos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hermano',
            name='curp',
            field=models.CharField(blank=True, max_length=18, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNION_LIBRE', 'Unión libre'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo')], max_length=20),
        ),
        migrations.AddField(
            model_name='hermano',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC'),
        ),
        migrations.CreateModel(
            name='NotaHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('DISCIPLINARIA', 'Disciplinaria'), ('GENERAL', 'General')], max_length=20)),
                ('contenido', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_hermanos_creadas', to=settings.AUTH_USER_MODEL)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='miembros.hermano')),
            ],
            options={
                'verbose_name': 'Nota del hermano',
                'verbose_name_plural': 'Notas del hermano',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='NombramientoLogial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.cargo')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombramientos_logiales', to='miembros.hermano')),
            ],
            options={
                'verbose_name': 'Nombramiento logial',
                'verbose_name_plural': 'Nombramientos logiales',
                'ordering': ['-vigente', '-periodo_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoriaHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='miembros.hermano')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria_hermanos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría del hermano',
                'verbose_name_plural': 'Eventos de auditoría del hermano',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IDENTIFICACION', 'Identificación'), ('CURP', 'CURP'), ('RFC', 'RFC'), ('COMPROBANTE_DOMICILIO', 'Comprobante de domicilio'), ('SOLICITUD', 'Solicitud'), ('ACTA_INICIACION', 'Acta de iniciación'), ('ACTA_AUMENTO', 'Acta de aumento'), ('ACTA_EXALTACION', 'Acta de exaltación'), ('OTRO', 'Otro documento')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='hermanos/documentos/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_hermanos_cargados', to=settings.AUTH_USER_MODEL)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='miembros.hermano')),
            ],
            options={
                'verbose_name': 'Documento del hermano',
                'verbose_name_plural': 'Documentos del hermano',
                'ordering': ['tipo', '-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='DistincionHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONDECORACION', 'Condecoración'), ('RECONOCIMIENTO', 'Reconocimiento')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distinciones', to='miembros.hermano')),
            ],
            options={
                'verbose_name': 'Distinción del hermano',
                'verbose_name_plural': 'Distinciones del hermano',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComisionHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='miembros.hermano')),
            ],
            options={
                'verbose_name': 'Comisión del hermano',
                'verbose_name_plural': 'Comisiones del hermano',
                'ordering': ['-vigente', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AdscripcionLogial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adscripciones_logiales', to='miembros.hermano')),
                ('logia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miembros.logia')),
            ],
            options={
                'verbose_name': 'Adscripción logial',
                'verbose_name_plural': 'Adscripciones logiales',
                'ordering': ['-vigente', '-fecha_inicio', '-id'],
            },
        ),
    ]
