# Generated by Django 5.2.6 on 2026-07-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('recibo', models.PositiveIntegerField(blank=True, null=True)),
                ('concepto', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('capitas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aniversario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saco_beneficencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taller_bj', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificacion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hermano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.hermano')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
