# Generated by Django 5.2.6 on 2026-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesoreria", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimiento",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="movimiento",
            name="justificacion",
        ),
        migrations.AddField(
            model_name="movimiento",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
    ]
