# Generated by Django 5.2.6 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0008_distribucioncapita_grupo"),
        ("negocio", "0002_pago_aplicacionpago"),
        ("tesoreria", "0002_remove_movimiento_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="concepto_contable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogos.conceptocontable",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_contables",
                to="negocio.pago",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimiento",
            constraint=models.UniqueConstraint(
                fields=("pago", "concepto_contable"),
                name="uq_movimiento_pago_concepto",
            ),
        ),
    ]
