# Generated by Django 5.2.6 on 2026-08-03 17:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0008_distribucioncapita_grupo'),
        ('negocio', '0002_pago_aplicacionpago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ejercicio Contable',
                'verbose_name_plural': 'Ejercicios Contables',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=12)),
                ('nivel', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('acepta_movimientos', models.BooleanField(default=True, help_text='Solo las cuentas de detalle (hoja) pueden recibir partidas.', verbose_name='Acepta movimientos')),
                ('activa', models.BooleanField(default=True)),
                ('concepto_contable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_contable', to='catalogos.conceptocontable')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('DIARIO', 'Diario')], max_length=10)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('origen', models.CharField(choices=[('PAGO', 'Pago'), ('MANUAL', 'Manual'), ('AJUSTE', 'Ajuste')], default='PAGO', max_length=10)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='contabilidad.ejerciciocontable')),
                ('elaborada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polizas_contables', to='negocio.pago')),
            ],
            options={
                'verbose_name': 'Póliza Contable',
                'verbose_name_plural': 'Pólizas Contables',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartidaPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('concepto', models.CharField(blank=True, default='', max_length=255)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabilidad.cuenta')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidad.poliza')),
            ],
            options={
                'verbose_name': 'Partida de Póliza',
                'verbose_name_plural': 'Partidas de Póliza',
                'ordering': ['poliza', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(condition=models.Q(('pago__isnull', False)), fields=('pago',), name='uq_poliza_por_pago'),
        ),
        migrations.AddConstraint(
            model_name='partidapoliza',
            constraint=models.CheckConstraint(condition=models.Q(('debe__gte', 0), ('haber__gte', 0)), name='ck_partida_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='partidapoliza',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debe__gt', 0), ('haber', 0)), models.Q(('debe', 0), ('haber__gt', 0)), _connector='OR'), name='ck_partida_debe_xor_haber'),
        ),
    ]
