# Generated by Django 5.2.6 on 2026-07-13 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0002_alter_conceptocontable_options_and_more"),
        ("miembros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Obligacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("LIQUIDADA", "Liquidada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.conceptocontable",
                    ),
                ),
                (
                    "hermano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miembros.hermano",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_vencimiento"],
            },
        ),
    ]
