# Generated by Django 5.2.6 on 2026-07-22 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_alter_hermano_grado'),
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('CANCELADO', 'Cancelado')], default='REGISTRADO', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miembros.hermano')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio.obligacion')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.pago')),
            ],
            options={
                'ordering': ['fecha_aplicacion'],
            },
        ),
    ]
