"""Alias de nombres usados en los movimientos históricos."""


ALIAS_MIEMBROS = {
    "VICTOR H. AMBROSIO": "VICTOR HUGO AMBROSIO GUEVARA",
    "GABINO SANTAMARIA": "GABINO SABITRI SANTAMARIA DELGADO",
    "GABINO S. SANTAMARIA": "GABINO SABITRI SANTAMARIA DELGADO",
    "DAVID GARCIA": "DAVID GARCIA MELGOZA",
    "ALEXIS GARCIA": "ALEXIS GUERRA GARCIA",
    "ALEXIS GARCIA MAY": "ALEXIS GUERRA GARCIA",
    "OMAR PACHECO": "JOSE OMAR PACHECO TAPIA",
    "ENRIQUE RAMON (MESERO)": "LUIS ENRIQUE RAMON VILLALBA",
    "ENRIQUE RAMON JUN": "LUIS ENRIQUE RAMON VILLALBA",
    "ENRIQUE RAMON JUL A NOV": "LUIS ENRIQUE RAMON VILLALBA",
    "J. ALFREDO GONZALEZ": "JOSE ALFREDO GONZALEZ SOLIS",
    "AULIO C. IBARRA": "AULIO CESAR IBARRA ZAVALA",
}
